### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by robert-wettstaedt** [shopware/swag-docs-storefront-assets#2]
**Entered command**
```
./psh.phar storefront:build
```

**Output**
```
###################

SHOPWARE Developer Version

       _
      | |
   ___| |__   ___  _ ____      ____ _ _ __ ___
  / __| '_ \ / _ \| '_ \ \ /\ / / _` | '__/ _ \
  \__ \ | | | (_) | |_) \ V  V / (_| | | |  __/
  |___/_| |_|\___/| .__/ \_/\_/ \__,_|_|  \___|
                  | |
                  |_|

Using .psh.yaml.dist extended by .psh.yaml.override

Starting Execution of 'storefront:build' ('/shopware6/dev-ops/storefront/actions/build.sh')


(1/4) Starting
> bin/console bundle:dump

	 [OK] Dumped plugin configuration.


(2/4) Starting
> PROJECT_ROOT=/shopware6/  npm --prefix vendor/shopware/platform/src/Storefront/Resources/ run production

	> sw-next-storefront@1.0.0 production /shopware6/vendor/shopware/platform/src/Storefront/Resources
	> NODE_ENV=production webpack --config webpack.config.js

	# Webpack Plugin Injector: Plugin "StorefrontAssets" injected as a new entry point
	# Webpack Plugin Injector: Plugin "PluginQuickStart" injected as a new entry point
	ℹ USING WEBPACK CONFIG FILE: ./build/webpack.prod.config.js

	ℹ Compiling Shopware 6 Storefront
	✔ Shopware 6 Storefront: Compiled with some errors in 16.70s
	   173 modules

	ERROR in /shopware6/custom/plugins/StorefrontAssets/src/Resources/storefront/styles/main.scss 1:5
	Module parse failed: Unexpected token (1:5)
	You may need an appropriate loader to handle this file type.
	> body {
	|     background: blue;
	| }
	events.js:174
	      throw er; // Unhandled 'error' event
	      ^

	Error: ENOENT: no such file or directory, open '/shopware6/platform/src/Storefront/Resources/dist/./js/storefront-assets.js'
	Emitted 'error' event at:
	    at lazyFs.open (internal/fs/streams.js:115:12)
	    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! sw-next-storefront@1.0.0 production: `NODE_ENV=production webpack --config webpack.config.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the sw-next-storefront@1.0.0 production script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /.npm/_logs/2019-07-24T10_17_30_213Z-debug.log

Execution aborted, a subcommand failed!
```

**Node version**
```
$ node -v && npm -v
v10.15.3
6.10.2
```

**System**
```
macOS 10.14.5 (18F132)
```

**Comment by jenskueper** [comment]
Hello,

thank you for the report. There is a mistake in the example. The .scss file can't be included in the JS anymore. We will fix it and come back to you.

Best regards
